### ISSUE TITLE
OroPlatform 2.0 Update

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Platform-legacy#12]
https://github.com/orocrm/platform/releases/tag/2.0.0

Master Issue track upgrade to BAP 2.0

**Comment by sadortun** [comment]
I've done the migration for Communication bundle, and part of its dependenceis,   i can push the changes to the existing PRs to the bundles, or if you can merge the PRs, i can open a new one after that

**Comment by StephenOTT** [comment]
@sadortun great!  lets get @mario-digitalstate involved and look to get those PRs added, and then we can do a fresh PR for the 2.0 update
