### ISSUE TITLE
Camunda sdk api missing

### ISSUE THREAD

**Issue by hb7777** [DigitalState/Platform-legacy#25]
I've installed Camunda  and can execute this command successfully
> php app/console bpm:camunda:start

When I tried this url **/portal/reset** I get this error message 

> Fatal error: Uncaught Error: Class 'org\camunda\php\sdk\Api' not found in /var/www/oroDsV2/vendor/digitalstate/platform-portal-bundle/Controller/Portal/ResetController.php on line 41

Are we missing some bundle in composer.json. The code at line 41 the  of ResetController is 

> $api = new \org\camunda\php\sdk\Api('http://localhost:8080/engine-rest');

Do we need to configure something in our webserver conf file, so that this url **http: //localhost: 8080/engine-rest** can work correctly?

**Comment by marioprudhomme** [comment]
While re-structuring the bundles into git submodules, the camunda sdk composer require got lost in translations. It has been fixed since.
