### ISSUE TITLE
Communications: Content Template Management

### ISSUE THREAD

**Issue by hb7777** [DigitalState/Platform-legacy#27]
The templates used by the city for all their communications, could turn out to be huge. So they may want a way to manage them efficiently, for example. All or several templates could share the same header, footer. They may be a need for several templates to share a common navigation choice of links, etc.

If for some reason the city needs to change the header, footer, navigation, etc. for all their current templates. They would want to prevent having to modify each template individually, but instead changing a few key files (header, footer, nav) that are used by all the templates, and avoid potential errors and workload that such a change could create.

**Comment by StephenOTT** [comment]
Okay so to clarify:

Template in this context is a Content Template; as in the template used when defining a specific piece of content that will populate a Message; Example: HTML with embedded css template for an email.

1. Ability to have ownership for ACL and filtering on who can use/access/manage which Content Templates.

1. Ability to have Taxonomies and Tags/terms that can be applied to Content Templates to make finding a template easier when building a communication (especially for users that have access to many content templates.

1. Ability to have shared template content that can be applied to multiple content templates; such as a header, footer, common text that is used in many different content templates. (To be reviewed further)

@hb7777 Is this correct?

**Comment by hb7777** [comment]
correct.

**Comment by StephenOTT** [comment]
@hb7777 lets move this into the https://github.com/DigitalState/Platform-Communication-Bundle.
