### ISSUE TITLE
Add /src/ to .gitignore

### ISSUE THREAD

**Issue by stefgosselin** [DigitalState/Platform-legacy#58]
Currently .gitignore has /src/Demo.  Could we consider ignoring at /src level?

**Comment by marioprudhomme** [comment]
Wouldn't that remove all our platform-based bundles? What are you trying to ignore additionally?

**Comment by stefgosselin** [comment]
are your platform bundles not in /vendor? ( or will be eventually ) ..

This is to ignore the custom namespaces in /src   (Montreal in our case)

**Comment by marioprudhomme** [comment]
Only the standalone/generic bundles are in vendor. The bundles related to the DS application core currently resides in src. 

I've added src/Demo to gitignore to ease development of demos. Did you want to add another "area" to ignore to ease your development?

**Comment by stefgosselin** [comment]
I would like to ignore /src/Montreal.  I tried in local .gitignore,  .gitconfig has a mapped local .gitignore

`
[core]
	excludesfile = /home/dev/.gitignore


It does not seem to work,  tried both relative and absolute path in local .gitignore.


>> I've added src/Demo to gitignore to ease development of demos. Did you want to add another "area" to ignore to ease your development?

Yes, anything over /src/Montreal would need to be ignored.
